name: Deploy docker images to Docker Hub

on:
  workflow_dispatch:

  push:
    branches:
      - stable

jobs:
  push_image:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - experimental: true
            tag: latest
            golang_image: golang:latest
          - experimental: true
            tag: "1.18"
            golang_image: golang:1.18
          - experimental: true
            tag: "1.17"
            golang_image: golang:1.17
          - experimental: false
            tag: "1.16"
            golang_image: golang:1.16

    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            GOLANG_IMAGE=${{ matrix.golang_image }}
            SWIFTLINT_IMAGE=tenshiamd/swiftlint:0.46.5
          context: .
          push: true
          tags: |
            tenshiamd/golang_flutter:${{ matrix.tag }}
